name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            cgo: 1
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            cgo: 1
            use_docker: true
          - os: macos-latest
            goos: darwin
            goarch: amd64
            cgo: 1
          - os: macos-latest
            goos: darwin
            goarch: arm64
            cgo: 1

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux' && matrix.use_docker != true
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev

      - name: Set up QEMU
        if: matrix.use_docker == true
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: matrix.use_docker == true
        uses: docker/setup-buildx-action@v3

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install libpcap

      - name: Install dependencies
        if: matrix.use_docker != true
        run: make mod

      - name: Install build tools
        if: matrix.use_docker != true
        run: make tools

      - name: Run tests
        if: matrix.goos == 'linux' && matrix.goarch == 'amd64'
        run: make test

      - name: Build binary (Docker ARM64)
        if: matrix.use_docker == true
        run: |
          VERSION=$(cat VERSION)
          COMMIT=$(git rev-parse HEAD)
          BUILD_DATE=$(date -u '+%Y-%m-%d_%H:%M:%S')
          
          # 创建 Dockerfile
          cat > Dockerfile.arm64 << 'EOF'
          FROM --platform=linux/arm64 golang:1.24-bullseye
          
          RUN apt-get update && apt-get install -y \
              libpcap-dev \
              && rm -rf /var/lib/apt/lists/*
          
          WORKDIR /build
          COPY . .
          
          RUN go mod download
          
          ENV CGO_ENABLED=1
          ENV GOOS=linux
          ENV GOARCH=arm64
          
          ARG VERSION
          ARG COMMIT
          ARG BUILD_DATE
          
          RUN go build \
              -ldflags="-s -w -X 'github.com/packetd/packetd/common.buildVersion=${VERSION}' -X 'github.com/packetd/packetd/common.buildTime=${BUILD_DATE}' -X 'github.com/packetd/packetd/common.buildHash=${COMMIT}'" \
              -o packetd .
          EOF
          
          # 使用 Docker 构建
          docker buildx build \
            --platform linux/arm64 \
            --build-arg VERSION="${VERSION}" \
            --build-arg COMMIT="${COMMIT}" \
            --build-arg BUILD_DATE="${BUILD_DATE}" \
            -f Dockerfile.arm64 \
            --output type=local,dest=. \
            .

      - name: Build binary (Native)
        if: matrix.use_docker != true
        run: |
          VERSION=$(cat VERSION)
          COMMIT=$(git rev-parse HEAD)
          BUILD_DATE=$(date -u '+%Y-%m-%d_%H:%M:%S')

          CGO_ENABLED=${{ matrix.cgo }} GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build \
            -ldflags="-s -w -X 'github.com/packetd/packetd/common.buildVersion=${VERSION}' -X 'github.com/packetd/packetd/common.buildTime=${BUILD_DATE}' -X 'github.com/packetd/packetd/common.buildHash=${COMMIT}'" \
            -o packetd .

      - name: Create archive
        run: |
          VERSION=$(cat VERSION)
          archive_name="packetd-${VERSION}-${{ matrix.goos }}-${{ matrix.goarch }}"
          tar -czf "${archive_name}.tar.gz" packetd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archive-${{ matrix.goos }}-${{ matrix.goarch }}
          path: packetd-*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: archive-*
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packetd-*.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}